// Base time units
const MILLISECONDS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;

const SECOND = MILLISECONDS_PER_SECOND;
const MINUTE = SECOND * SECONDS_PER_MINUTE;
const HOUR = MINUTE * MINUTES_PER_HOUR;

export const TIMER_INCREMENT_MS = 0.01;
export const TIMER_UPDATE_INTERVAL_MS = 10;
export const MIN_HOLD_DURATION_MS = SECOND;
export const MAX_PROGRESS_PERCENTAGE = 100;

export {
  MILLISECONDS_PER_SECOND,
  SECONDS_PER_MINUTE,
  MINUTES_PER_HOUR,
  SECOND,
  MINUTE,
  HOUR,
};
